### ISSUE TITLE
SafeArea Problem

### ISSUE THREAD

**Issue by hasimyerlikaya** [hey24sheep/uiblock#1]
Hi,

Thank you for this package.

Since SafeArea is used in the resulting model, it looks bad in my application. 
Is it possible to remove SafeArea or make it optional?

![image](https://user-images.githubusercontent.com/7986394/102353418-0e38c300-3fba-11eb-84da-4b2555e6e227.png)

**Comment by hey24sheep** [comment]
Hi, you could use UIBlock as widget to overcome this problem as it doesn't use the default block modal. I have just updated the package in respect to this and now you can customize or totally disable the safe area. Let me know if this fixes your problem.

**Comment by hasimyerlikaya** [comment]
It was enough for me.
Now we can customize it as we want, it just got better.

Thank you.
