### ISSUE TITLE
Background Fade Effect

### ISSUE THREAD

**Issue by hasimyerlikaya** [hey24sheep/uiblock#2]
Hi again,

I think the fade effect must be added to the background. 
Background sliding to the top but always the same opacity.
If you can add a fade effect, will be much nice.

**Comment by hasimyerlikaya** [comment]
I need something else. Can you add a function to catch the pop event? :)

![image](https://user-images.githubusercontent.com/7986394/102706196-cc04cf80-42a0-11eb-8f9d-d2c5913f90b3.png)

**Comment by hey24sheep** [comment]
Closing in respect to 7450197. Also, a side note - you can change opacity anytime read the faq and properties in readme.

**Comment by hasimyerlikaya** [comment]
Thank you :)
