### ISSUE TITLE
onPop Event

### ISSUE THREAD

**Issue by hasimyerlikaya** [hey24sheep/uiblock#3]
Can you add onPop event?
I need to handle view pop event, doing something relative to that.

Thank you.

**Comment by hey24sheep** [comment]
There is no need for a pop event. You have a uiblock.hide(). You can do anything before or after this. If you are using it as a widget then you can whenever you have a show loader function you can do whatever you want in that.

**Comment by hasimyerlikaya** [comment]
Ther is a "canDissmissOnBack" options.
Users can dismiss by tap back buton.
In this use case, we need to handle the onPop event.

![image](https://user-images.githubusercontent.com/7986394/103164441-3925e100-481c-11eb-9cbc-10d061fbdf7e.png)

**Comment by hey24sheep** [comment]
First, try not to post image instead post your code. Second, You are doing UIBlock.block right? it won't pop on its own. You do UIBlock.unblock so when you do this, you do whatever you want before that. 

I cannot call onPopHandler passed to UIBlock from UIUnblock, those functions are just static helpers and they do not maintain anything. I hope you understand what I am saying. Look at [this example](https://github.com/hey24sheep/uiblock/blob/master/example/lib/main.dart#L196), you will understand what I am saying.

**Comment by hey24sheep** [comment]
Try to put your code instead of image. I will look into it. It will still arise an issue for you with data as well. Hardware back and programmatic back won't be distinguished. So, your data for return will same on hardware back.

**Comment by hasimyerlikaya** [comment]
The image was just to show the parameter. 
There was no code to run. 
I think it would be better if I did my own implementation.
Thank you.

**Comment by hey24sheep** [comment]
Tell me one thing. What will happen if the case is your code is only dependent on user back?

``` dart

Widget _buildDefaultDissmissible(BuildContext context) {
    return Container(
      child: FlatButton(
        child: Text(
          "Default UIBlock (Dissmiss Enabled)",
          textAlign: TextAlign.center,
        ),
        onPressed: () async {
          var result = UIBlock.blockWithData(
            _scaffoldGlobalKey.currentContext,
            canDissmissOnBack: true,
            loadingTextWidget: Padding(
              padding: const EdgeInsets.all(8.0),
              child: Text(
                'Press back to dissmiss',
                textAlign: TextAlign.center,
                style: TextStyle(
                  color: Colors.white,
                  fontSize: 18.0,
                  fontWeight: FontWeight.w600,
                ),
              ),
            ),
          );

          print(result);
        },
      ),
    );
  }
  
 /// blocks complete ui
  /// do not forget to call unblock after this
  static Future<T> blockWithData<T>(
    BuildContext context, {
    ChildBuilder childBuilder,
    Widget customLoaderChild,
    Widget loadingTextWidget,
    Color backgroundColor,
    bool canDissmissOnBack,
    ImageFilter imageFilter,
    bool safeAreaLeft,
    bool safeAreaTop,
    bool safeAreaRight,
    bool safeAreaBottom,
    EdgeInsets safeAreaMinimumPadding,
    bool safeAreaMaintainBottomViewPadding,
    bool isSlideTransitionDefault = true,
    BuildBlockModalTransitions customBuildBlockModalTransitions,
  }) async {
    return await Navigator.of(context).push<T>(
      UIBlockModal<T>(
        childBuilder: childBuilder,
        customLoaderChild: customLoaderChild,
        loadingTextWidget: loadingTextWidget,
        backgroundColor: backgroundColor,
        canDissmissOnBack: canDissmissOnBack,
        imageFilter: imageFilter,
        left: safeAreaLeft,
        top: safeAreaTop,
        right: safeAreaRight,
        bottom: safeAreaBottom,
        minimum: safeAreaMinimumPadding,
        maintainBottomViewPadding: safeAreaMaintainBottomViewPadding,
        isSlideTransitionDefault: isSlideTransitionDefault,
        buildBlockModalTransitions: customBuildBlockModalTransitions,
      ),
    );
  }

  /// unblocks previously called block with return data
  static void unblockWithData(BuildContext context, dynamic onPopData) {
    Navigator.of(context).pop([context, onPopData]);
  }

```

Take this example I have coded. What should happen in this case?

**Comment by hey24sheep** [comment]
Also, have a look here. I have done something similar for my other [package](https://github.com/hey24sheep/backdrop_modal_route) it might help you instead of this package.

**Comment by hey24sheep** [comment]
Let me know if my sample above is useful or not. If not I will remove it otherwise I will add it to the package.

**Comment by hasimyerlikaya** [comment]
I use it like this, I show the user a warning and then a screen is open at the back. If the user presses the back button after the warning, I want both the UIBlock and the back window to be closed.

I don't need any data return, just know when it shuts down.

**Comment by hey24sheep** [comment]
Okay, I got your point. I am sorry, I half brain replied to your issue. I have added this and updated the package in respect ca2e0a9

I hope this helps you. Thanks 👍🏼

**Comment by hasimyerlikaya** [comment]
Thank you, 
I was testing the exact solution you suggested by adding it locally. 
It was better for you to include it in the project.
